apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hello-svc.fullname" . }}-config
data:
  READY_DELAY_MS: {{ .Values.env.READY_DELAY_MS | quote }}
  HTTP_THREADS: {{ .Values.env.HTTP_THREADS | quote }}
