{{- $sa := .Values.serviceAccount | default dict -}}
{{- if ($sa.create | default false) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "hello-svc.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-svc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
